services:
  qdrant:
    build: .
    container_name: qdrant_api
    ports:
      - "3013:3013"
    volumes:
      - ./app:/app # Scripts
      - ../data:/app/data # Data
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
